---
# tasks file for firewall

- name: Ensure firewall configuration 
  ansible.posix.firewalld: 
    zone: "{{ item['zone'] | default(omit) }}"
    permanent: true 
    immediate: true
    state: "{{ item['state'] | default('enabled') }}"
    port: "{{ item['port'] }}"
  loop: "{{ firewall_rules }}"
  notify: reload firewalld 
  when: item['port'] is defined 
  become: true