- name: install apache
  ansible.builtin.dnf:
    name: httpd 
    state: present

- name: start and enable service 
  ansible.builtin.service: 
    name: httpd
    enabled: true 
    state: started 
